assumptions-rules:

  default-rules:
    - rule: 'default_noens'
      filter:
        is-ensamble: 0

      time-assumption:
        product-definition-template-number: 0
        type-of-time-range: 'instant'

    - rule: 'default_ens'
      filter:
        is-ensamble: 1

      time-assumption:
        product-definition-template-number: 1
        type-of-time-range: 'instant'


  special-rules:
    - rule: 'max_since_last_pp_noens'
      filter:
        paramId:  [ 49, 201, 228226 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'max'
        emit-step-zero: False

    - rule: 'max_since_last_pp_ens'
      filter:
        paramId:  [ 49, 201, 228226 ]
        is-ensamble: True

      product-definition-template-number: 11

      time-assumption:
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'max'
        emit-step-zero: False


    - rule: 'min_since_last_pp_noens'
      filter:
        paramId:  [ 202, 228227 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'min'
        emit-step-zero: False

    - rule: 'min_since_last_pp_ens'
      filter:
        paramId:  [ 202, 228227 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'min'
        emit-step-zero: False


    - rule: 'max_over_last_3_hours_noens'
      filter:
        paramId:  [ 228026, 228028, 228222 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'max'
        emit-step-zero: False

    - rule: 'max_over_last_3_hours_ens'
      filter:
        paramId:  [ 228026, 228028, 228222 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'max'
        emit-step-zero: False



    - rule: 'min_over_last_3_hours_noens'
      filter:
        paramId:  [ 228027, 228223 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'min'
        emit-step-zero: False

    - rule: 'min_over_last_3_hours_ens'
      filter:
        paramId:  [ 228027, 228223 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'min'
        emit-step-zero: False




    - rule: 'max_over_last_6_hours_noens'
      filter:
        paramId:  [ 121, 123, 228224, 228035, 228036 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'max'
        emit-step-zero: False

    - rule: 'max_over_last_6_hours_ens'
      filter:
        paramId:  [ 121, 123, 228224, 228035, 228036 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'max'
        emit-step-zero: False




    - rule: 'min_over_last_6_hours_noens'
      filter:
        paramId:  [ 122, 228225 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'min'
        emit-step-zero: False

    - rule: 'min_over_last_6_hours_ens'
      filter:
        paramId:  [ 122, 228225 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'min'
        emit-step-zero: False





    - rule: 'average_over_last_1_hour_noens'
      filter:
        paramId:  [ 228051, 228053 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'average'
        emit-step-zero: False

    - rule: 'average_over_last_1_hour_ens'
      filter:
        paramId:  [ 228051, 228053 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'average'
        emit-step-zero: False


    - rule: 'average_over_last_3_hours_noens'
      filter:
        paramId:  [ 228057, 228059 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'average'
        emit-step-zero: False

    - rule: 'average_over_last_3_hours_ens'
      filter:
        paramId:  [ 228057, 228059 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'average'
        emit-step-zero: False




    - rule: 'average_over_last_6_hours_noens'
      filter:
        paramId:  [ 228058, 228060 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'average'
        emit-step-zero: False

    - rule: 'average_over_last_6_hours_ens'
      filter:
        paramId:  [ 228058, 228060 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'average'
        emit-step-zero: False




    - rule: 'mode_over_last_1_hour_noens'
      filter:
        paramId:  [ 260320 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'mode'
        emit-step-zero: False

    - rule: 'mode_over_last_1_hour_ens'
      filter:
        paramId:  [ 260320 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'mode'
        emit-step-zero: False



    - rule: 'mode_over_last_3_hours_noens'
      filter:
        paramId:  [ 260321 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'mode'
        emit-step-zero: False

    - rule: 'mode_over_last_3_hours_ens'
      filter:
        paramId:  [ 260321 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'mode'
        emit-step-zero: False



    - rule: 'mode_over_last_6_hours_noens'
      filter:
        paramId:  [ 260339 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'mode'
        emit-step-zero: False

    - rule: 'mode_over_last_6_hours_ens'
      filter:
        paramId:  [ 260339 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'mode'
        emit-step-zero: False




    - rule: 'severity_over_last_1_hour_noens'
      filter:
        paramId:  [ 260318 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'severity'
        emit-step-zero: False

    - rule: 'severity_over_last_1_hour_ens'
      filter:
        paramId:  [ 260318 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 1
        type-of-statistical-process: 'severity'
        emit-step-zero: False




    - rule: 'severity_over_last_3_hours_noens'
      filter:
        paramId:  [ 260319 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'severity'
        emit-step-zero: False

    - rule: 'severity_over_last_3_hours_ens'
      filter:
        paramId:  [ 260319 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 3
        type-of-statistical-process: 'severity'
        emit-step-zero: False




    - rule: 'severity_over_last_6_hours_noens'
      filter:
        paramId:  [ 260338 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'severity'
        emit-step-zero: False

    - rule: 'severity_over_last_6_hours_ens'
      filter:
        paramId:  [ 260338 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'fixed-size'
        length-of-time-range-in-hours: 6
        type-of-statistical-process: 'severity'
        emit-step-zero: False


    - rule: 'accumulation_since_last_pp_noens'
      filter:
        paramId:  [ 8, 9, 20, 44, 45, 47, 50, 57, 58, 142:144, 145:147, 169, 175:181, 189, 195:197, 205, 208, 209, 211:213, 228, 239, 240, 162100:162113, 222001:222256, 228021, 228022, 228080:228082, 228129, 228130, 228216, 228251, 233000:233035 ]
        is-ensamble: False

      time-assumption:
        product-definition-template-number: 8
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'accumulation'
        emit-step-zero: False

    - rule: 'accumulation_since_last_pp_ens'
      filter:
        paramId:  [ 8, 9, 20, 44, 45, 47, 50, 57, 58, 142:144, 145:147, 169, 175:181, 189, 195:197, 205, 208, 209, 211:213, 228, 239, 240, 162100:162113, 222001:222256, 228021, 228022, 228080:228082, 228129, 228130, 228216, 228251, 233000:233035 ]
        is-ensamble: True

      time-assumption:
        product-definition-template-number: 11
        type-of-time-range: 'from-last-pp'
        type-of-statistical-process: 'accumulation'
        emit-step-zero: False